import localFont from 'next/font/local';
import './globals.css';
import { ReactNode } from 'react';
import { AuthProvider } from '@/context/AuthContext';
import { NextAuthProvider } from '@/context/SessionProvider';

export const metadata = {
  title: 'TDD App',
  description: 'Generated by create next app',
};

const neueLeiden = localFont({
  src: '../public/fonts/NeueLeiden-Regular.woff2',
  variable: '--font-NeueLeiden',
});

interface IProps {
  children: ReactNode;
}

const neueLeidenbold = localFont({
  src: '../public/fonts/NeueLeiden-Bold.woff2',
  variable: '--font-NeueLeidenBold',
});

export default function RootLayout({ children }: IProps) {
  return (
    <html
      lang="en"
      className={`${neueLeiden.variable} ${neueLeidenbold.variable}`}
    >
      <body className="bg-lightGreen font-neueLeiden">
        <AuthProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
